kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: grafana-operator-system


generatorOptions:
  disableNameSuffixHash: true


configMapGenerator:
  - name: grafana-dashboard-dora-metrics
    files:
      - dashboards/dora-dashboard.json